### PR TITLE
Issue #24 Correct display in Safari

### PR DESCRIPTION
**Pull request by infograf768**
https://github.com/ranbuch/accessibility/issues/24

Missing + in the js

### CODE REVIEW

**Comment by brianteeman** [comment]
1. Surely this  change should be made in the src not the dist?
2. Are you sure that it should be font-family: Material+Icons? All the google documentation says not. I think you may be confused with the fontFaceSrc

**Comment by infograf768** [comment]
@ranbuch 
As I was not much aware about this repo, I may have incorrectly patched the minified js instead of the `main.js`
So the correction there would be line 26
`        fontFamily: 'Material Icons',`
to
        `fontFamily: 'Material+Icons',`
        
  :)

**Comment by infograf768** [comment]
> Are you sure that it should be font-family: Material+Icons?

Yes. Try it for yourself.  The `+` is taken off is the resulting css.
Safari screen capture
Screenshot 2021-12-16 at 09 49 11

**Comment by brianteeman** [comment]
I say again font-family should have a space in it.
It is fontFaceSrc that should use the +

read the docs https://developer.mozilla.org/en-US/docs/Web/CSS/font-family

**Comment by infograf768** [comment]
Read https://github.com/joomla/joomla-cms/issues/36311#issuecomment-995641561 about the redundant font-family.

Safari is real picky. The + is necessary or the the redundant css font-family has to be deleted from the js.

**Comment by ranbuch** [comment]
@infograf768 many thanks for your effort. For some reason I can see the change only on the [dist/accessibility.min.js](https://github.com/ranbuch/accessibility/pull/27/commits/0997a39b3b62e1fe1ca458c5f586ec08f442e2d5) but not on `src/main.js`. Can you please add the `+` sign there as well?

If not, I can do it myself. Anyways, nice catch. Thanks again.

**Comment by angieradtke** [comment]
Hi guys - maybe offtopic here: but can somebody explain me why the openicon is an <i> instead of a button?

**Comment by infograf768** [comment]
@ranbuch 
`main.js` also modified now.

**Comment by ranbuch** [comment]
Thanks @infograf768 merged.
@angieradtke Yes, we should use `button` instead if `li` for better accessibility. Let's keep this issue open for now so I won't forget and implement it when I'll find the time to do so.
Thanks all!

**Comment by angieradtke** [comment]
https://github.com/joomla/joomla-cms/issues/36311#issuecomment-996043196
https://github.com/angieradtke/Accessibility-plugin-icons/blob/main/README.md

**Pull request merged**
