### PR TITLE
Reformat main.ts +  Fix resize of text when size is declared in body css element

### PR DESCRIPTION
**Pull request by matandobr**
Fix resize of text when size is declared in body css element

### CODE REVIEW

**Comment by matandobr** [comment]
Hey @ranbuch 
I faced an issue the resize of text is not working when I declare the font size in the body element...
I think this fixes the issue

**Comment by ranbuch** [comment]
Hi @matandobr , thank you for your contribution.

The code from line `1397` to `1405` looks good but can you not format the whole file? Or, if you want, you can config your formatting preferences to the project.

Thanks.

**Comment by ranbuch** [comment]
I've manually copied your code, thank you @matandobr for your contribution!

**Comment by matandobr** [comment]
@ranbuch Sorry for the delay, thank you!

**Pull request closed without merging**
