### PR TITLE
New system of hotkeys

### PR DESCRIPTION
**Pull request by SeFeX**
Added a new system to add shortcut keys and enable dynamically

*Enable/Disable*
options.hotkeys.enabled = true/false

By default is disabled

- toggleMenu: ctrl + alt + a
- invertColors: ctrl + alt + i
- grayHues: ctrl + alt + g
- underlineLinks: ctrl + alt + u
- bigCursor: ctrl + alt + c
- readingGuide: ctrl + alt + r
- textToSpeech: ctrl + alt + t
- speechToText: ctrl + alt + s

And you can disable the title of the buttons with options.hotkeys.helpTitles = false

### CODE REVIEW

**Comment by ranbuch** [comment]
Thanks!

**Comment by brianteeman** [comment]
Is this enabled on your demo site https://ranbuch.github.io/accessibility/ and in the 3.0.1 release?

**Comment by ranbuch** [comment]
> Is this enabled on your demo site https://ranbuch.github.io/accessibility/ and in the 3.0.1 release?

Yes, I should probably add some small description on every button for the hotkey combination.

**Comment by ranbuch** [comment]
[related](https://github.com/ranbuch/accessibility/issues/10)

**Pull request merged**
